services:
  weather-api:
    build: .
    container_name: weather-gist-api

    ports:
      - "8000:8000"

    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

    volumes:
      - .:/app   

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    restart: unless-stopped